[ADD] 인증 기능 및 정보 조회 기능 추가
KangHayeonn/pickplace-server pull request #49
Opened 2023-07-15 03:35 UTC by sohyun-99

## 작업사항
- 회원가입 
- 로그인 
- 이메일 중복 체크 
- 토큰 재발급
- 로그아웃
- 회원탈퇴
- 내 정보  조회 
- 내 정보 수정
- jwt 적용
- redis 적용 (local redis)
- 
## 비고
- 메일링 , 소셜 로그인 제외한 부분 pr
- spring secrutiy 수정 예정

## Github 이슈

## 작업일자
- 2023.07-17
<br>

2023-07-17 13:54 UTC, hurontrara approved these changes
고생 많으셨습니다!

2023-07-17 23:27 UTC, KangHayeonn requested changes
우선 System.out.println 부분과 불필요한 주석처리는 제거해주시기 바랍니다!
기능 동작이 완료된 값들을 기준으로 최소한의 내용 설명이 필요한 주석만 남겨주세요!

2023-07-17 23:27 UTC, KangHayeonn commented on .github/workflows/deploy.yml
> +      - run: echo "${{secrets.APPLICATION}}" > ./src/main/resources/application.properties
오 이런식으로 배포시에 secret에서 경로를 찾아서 넣어주는 군요!!👍

2023-07-17 23:27 UTC, KangHayeonn commented on .github/workflows/deploy.yml
> +          path: ./src/main/resources/application.properties
이렇게 넣어준 값을 불러와서 쓰구요!! 좋은 팁 배워갑니다 🥰

2023-07-17 23:27 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/auth/controller/LoginController.java
> +////    }
위에 있는 authController에 있는 로그인과 이것은 무슨 차이가 있나요?

2023-07-17 23:27 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/auth/service/AuthService.java
> +//        Member member = new Member(request);
이 부분을 연결해서 사용하는 것이 더 좋을 것 같습니다! 예외처리와 함께
그리고 회원이 이미 존재하는 경우 null 보다는 exception handler를 해주는 것이 좋을 것 같습니다.

2023-07-17 23:27 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/auth/service/AuthService.java
> +//        return member.getEmail();
회원가입 시에 입력 값에 대한 validation이 들어가야 될 것 같습니다!

2023-07-17 23:27 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/config/SpringSecurityConfig.java
> +                .and()
API 명세서 확인 후 accesstoken으로 접근 인증 확인이 필요없는 `/api/v1/search`와 같은 api들도 permitAll을 해주시는 것이 좋을 것 같습니다!

2023-07-17 23:27 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/member/controller/MemberController.java
> +				if (error.getDefaultMessage().equals("공백")){
System  출력 부분은 삭제하고 올려주세요!

2023-07-17 23:27 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/member/controller/MemberController.java
> +		if (emailCheckResponse==true)
Ditto

2023-07-17 23:27 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/member/controller/MemberController.java
> +		String payload = new String(decoder.decode(payloadJWT));
decode하는 부분은 jwt 부분에서 함수로 만들고 불러와서 사용해도 깔끔할 것 같습니다!

2023-07-17 23:27 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/member/error/MemberExceptionHandler.java
> +        }
global exception을 활용하는 방식을 고려해보시면 좋을 것 같습니다.

2023-07-17 23:27 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/member/service/MemberInfoService.java
> +
Ditto

2023-07-17 23:27 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/member/service/MemberService.java
> +
Ditto

만약에 직접적인 테스트가 필요하다면 디버깅이나 로깅을 이용하시는 게 좋을 것 같습니다!

2023-07-17 23:27 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/member/service/MemberService.java
> +
Ditto

2023-07-17 23:27 UTC, KangHayeonn commented on src/main/resources/application-dev.properties
> +JWT.SECRET=SeCrEtKeY4HaShInGasdqwrerfwrgrwerwfvxcvsdsdfsdfsdf
저희 지금 application-dev.properties 부분이 업로드 되고 있는 것 같습니다.
확인 부탁드립니다!

2023-07-18 00:47 UTC, KangHayeonn approved these changes
확인했습니다!!
다음에는 조금 더 기능을 분기처리해서 업로드해주시면 더 효율적인 코드리뷰가 될 수 있을 것 같습니다!! 🥰🙏
고생하셨습니다 ㅎㅎ

2023-07-18 09:48 UTC, merged