[WIP] [ADD] 예약 도메인
KangHayeonn/pickplace-server pull request #55
Opened 2023-07-17 03:34 UTC by hurontrara

## 작업사항
- 내용을 적어주세요.

## 비고
- 내용을 적어주세요.

## Github 이슈
- 내용을 적어주세요.

## 작업일자
- 내용을 적어주세요. (예시: 2023.05.27)

<br>

2023-07-20 01:15 UTC, KangHayeonn requested changes
컨트롤러에 있는 비즈니스 로직들을 확인해주세요! 
그리고 혹시라도 null이나 특정 속성값이 안들어왔을 경우의 예외처리가 잘되어 있는지도 한번 체크 부탁드립니다! 🙏

2023-07-20 01:15 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +        BankResponse bankResponse = BankResponse.builder().bankName(bankName).bankNum(bankNum).build();
이 부분도 bankName이 없을 경우 에러가 발생할 것 같습니다!

2023-07-20 01:15 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +            throw new ReservationException(ReservationErrorResult.NO_MATCH_BANK_ACCOUNT);
👍

2023-07-20 01:15 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +        String url = "https://pickplace.kr/payment?code=" + uuid;  // 결제 비밀번호 입력하는 링크로...
이 부분은 테스트가 필요할 것 같은데 
우선 해당 url에 대해 환경 변수로 처리해주시면 더 좋을 것 같습니다!

2023-07-20 01:15 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +        if (memberPassword != qrPasswordRequest.getQrPassword()) {
근데 저희 예외처리 및 비즈니스 로직들이 service가 아닌 controller에 모두 작성이 되어있는데 이유가 있을까요?

2023-07-20 01:15 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +            bankNum = "1020315-12108542";
이 부분은 따로 enum 을 만들어서 사용하는 것이 더 좋을 것 같습니다! 
그리고 컨트롤러단에 있으면 안될 것 같습니다.. 
컨트롤러단은 진짜 최소한의 연결 역할만 해주는 것이 좋습니다!!

2023-07-20 01:15 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +    private int calculateVerificationCode(String cardNumber) {
Ditto

2023-07-20 01:15 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +    private Map<String, Object> getPayloadMap(String accessToken) {
Ditto

2023-07-20 01:15 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/reservation/error/ReservationErrorResult.java
> +    WRONG_CARD_NUMBER(HttpStatus.BAD_REQUEST, "Invalid card number."),
여기서 작성된 에러 메세지를 기준으로 프론트엔드에 보여줄 것인데 한국어가 아닌 영어로 통일된 걸까요? 
백엔드 분들끼리 에러메시지 언어형식을 통일화 시켜야할 것 같습니다!

2023-07-20 01:15 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/reservation/repository/ReservationRepositoryCustomImpl.java
> +public class ReservationRepositoryCustomImpl implements ReservationRepositoryCustom {
해당 파일은 어떤 역할을 하는 기능일까요? 😲

2023-07-20 16:01 UTC, hurontrara commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +        Map<String, Object> reservationPageMapByEmailAndRoomId = reservationService.getReservationPageMapByEmailAndRoomId(email, roomId);
시큐리티에서 한번 범위 내여서, 유효한 토큰입니다!

2023-07-20 16:03 UTC, hurontrara commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +        BankResponse bankResponse = BankResponse.builder().bankName(bankName).bankNum(bankNum).build();
```
    @NotBlank
    private String bankName;
```

'아이스티' 같은 이상한 문자가 들어올 경우 getBankNumByBankName 메서드에서 예외 처리하도록 하였습니다!

2023-07-20 16:06 UTC, hurontrara commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +        String url = "https://pickplace.kr/payment?code=" + uuid;  // 결제 비밀번호 입력하는 링크로...
넵 알겠습니다!

추후에 링크 알려주시면, 그때 환경변수 처리하도록 하겠습니다~

2023-07-20 16:27 UTC, hurontrara commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +        if (memberPassword != qrPasswordRequest.getQrPassword()) {
서비스 계층 거치기 귀찮아서... 리포지토리 계층에 바로 접근하는 식으로 짜봤습니다 ㅎㅎ..

죄송합니다 ㅠ_ㅠ

2023-07-20 16:36 UTC, hurontrara commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +            bankNum = "1020315-12108542";
넵 수정하였습니다

2023-07-20 16:46 UTC, hurontrara commented on src/main/java/com/server/pickplace/reservation/repository/ReservationRepositoryCustomImpl.java
> +public class ReservationRepositoryCustomImpl implements ReservationRepositoryCustom {
스프링 데이터 jpa의 레포지토리(ReservationRepository)에게 상속해주는 ReservationRepositoryCustom 의 구현체 입니다.

이렇게 구현해놓음으로써 스프링 빈으로서 사용되는 스프링 데이터 jpa의 레포지토리는 

스프링 데이터 jpa 레포지토리의 고유 기능 + 커스텀된 기능(querydsl과 같은) 을 모두 사용할 수 있게 됩니다!

2023-07-20 16:47 UTC, hurontrara commented on src/main/java/com/server/pickplace/reservation/error/ReservationErrorResult.java
> +    WRONG_CARD_NUMBER(HttpStatus.BAD_REQUEST, "Invalid card number."),
얘기 나눠보겠습니다!

2023-07-21 12:42 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +        BankResponse bankResponse = BankResponse.builder().bankName(bankName).bankNum(bankNum).build();
bankName이 null일 경우는 어떻게 예외처리 되나요?

2023-07-21 12:49 UTC, KangHayeonn approved these changes
확인했습니다!
고생하셨습니다! ㅎㅎ
추가 코드리뷰만 확인해주세요!! 😌

2023-07-21 12:49 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> -            bankNum = "1020315-12108542";
null check 없이 equals 비교를 바로 하게 되면 null 이 들어왔을 경우 바로 에러로 직결될 것 같습니다!

2023-07-21 12:49 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/reservation/entity/BankStatus.java
> +    URI("우리은행", "4020315-12108542");
해당 내용, 즉 고정 입력값에 대해서는 Swagger나 노션에 남겨놓으면 좋을 것 같습니다!

2023-07-21 14:21 UTC, hurontrara commented on src/main/java/com/server/pickplace/reservation/controller/ReservationController.java
> +        BankResponse bankResponse = BankResponse.builder().bankName(bankName).bankNum(bankNum).build();
@notblank가 널인 경우까지 검증합니다!

2023-07-21 14:24 UTC, hurontrara commented on src/main/java/com/server/pickplace/reservation/entity/BankStatus.java
> +    URI("우리은행", "4020315-12108542");
넵 노션에 남겨두었습니다

2023-07-21 14:25 UTC, merged