[ADD] 카카오톡 소셜 로그인 기능 추가
KangHayeonn/pickplace-server pull request #62
Opened 2023-07-19 11:47 UTC by sohyun-99

## 작업사항
- 카카오 소셜 로그인.

## 비고
- 내용을 적어주세요.

## Github 이슈
- 내용을 적어주세요.

## 작업일자
- 2023.07.20

<br>

2023-07-20 01:30 UTC, KangHayeonn requested changes
코드리뷰 확인 부탁드립니다!

2023-07-20 01:30 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/config/SpringSecurityConfig.java
> +//                    .antMatchers("/api/v1/members/**","/send-mail/pwd").permitAll() // /members 관련 api 허락
모든 도메인을 다 허용해주면 안될 것 같습니다! 
이부분도 같이 수정해서 올려주세요!

2023-07-20 01:30 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/socialLogin/kakao/service/KakaoUserService.java
> +        System.out.println("굿1");
System 부분은 삭제하고 올려주세요

2023-07-20 01:30 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/socialLogin/kakao/service/KakaoUserService.java
> +        body.add("client_id", "17daada2a5511b9f5ad422950ad1c268");
환경 변수 처리 해주셔야 할 것 같습니다!

2023-07-20 01:30 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/socialLogin/kakao/service/KakaoUserService.java
> +        body.add("client_secret", "VODb154UxG9n1uWAJ3UFvpEpfeT3vK3Y");
Ditto

2023-07-20 01:30 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/socialLogin/kakao/service/KakaoUserService.java
> +        log.info("hello");
log는 서비스에서 디버깅할 때 중요한 정보로 좀 더 유의미하게 작성하는 것이 좋을 것 같습니다.

2023-07-20 01:30 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/socialLogin/kakao/service/KakaoUserService.java
> +                    .email(kakaoEmail)
여기서 일반 로그인인지 소셜로그인인지 소셜 로그인 중에는 어떤 소셜인지에 대한 구분 값이 있는 속성이 들어가야할 것 같습니다! 
 
예를들어 loginType : common, kakao, naver , google  

그 타입에 따른 이메일 중복체크가 들어가야 할 것 같아요!

2023-07-21 10:41 UTC, hurontrara approved these changes
고생하셨습니다!

2023-07-28 05:24 UTC, KangHayeonn approved these changes
확인했습니다!
고생하셨습니다 ㅎㅎ

2023-07-28 05:26 UTC, merged