[ADD] 리뷰 도메인
KangHayeonn/pickplace-server pull request #67
Opened 2023-07-19 15:11 UTC by hurontrara

## 작업사항
- 리뷰 도메인 API 설계 및 구현

## 비고
- reservation 으로의 머지 후, develop으로 머지 예정 -> reservation 머지 후 pull로 가져온 후 develop으로 바로 머지 예정

## Github 이슈
- https://github.com/KangHayeonn/pickplace-server/issues/66

## 작업일자
- 2023.7.18 ~ 2023.7.21

<br>

2023-07-20 01:39 UTC, KangHayeonn requested changes
코드리뷰 확인해주세요!

2023-07-20 01:39 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/review/controller/ReviewController.java
> +        List<ReviewResponse> reviewRespons =  reviewRepository.getReviewDtosByEmail(email);
Respons 가 어떤 단어를 지칭하는걸까요?

2023-07-20 01:39 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/review/controller/ReviewController.java
> +        reviewListMap.put("reviewList", reviewRespons);
이 부분을 왜 map 형식으로 처리하는지 알 수 있을까요?

2023-07-20 01:39 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/review/controller/ReviewController.java
> +        reviewRepository.amendReview(email, amendReviewRequest, reviewId);
amendReview 보다는 더 개발적의미에서 통용적으로 쓰이는 단어를 쓰는 것이 좋을 것 같습니다!

2023-07-20 01:39 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/review/controller/ReviewController.java
> +        reviewRepository.deleteReview(email, reviewId);
예외처리를 해주지 않고 바로 삭제를 하나요? 
 
해당 이메일이 존재하는지 또는 해당 리뷰아이디가 존재하는지 그 리뷰를 작성한 작성자의 이메일이 맞는지 
 
추가로 이메일이 아닌 유저 아이디를 통해 확인을 거쳐야 할 것 같습니다.

2023-07-20 01:39 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/search/config/SearchMockUpSetting.java
> +            log.info("------------------------------");
로그는 디버깅할 때 사용하는 정말 중요한 단서이기 때문에 좀 더 유의미하게 남겨놓는 것이 좋을 것 같습니다.

2023-07-21 14:29 UTC, hurontrara commented on src/main/java/com/server/pickplace/review/controller/ReviewController.java
> +        List<ReviewResponse> reviewRespons =  reviewRepository.getReviewDtosByEmail(email);
```
List<ReviewResponse> reviewResponse =  reviewRepository.getReviewDtosByEmail(email);
```
오타입니다 ㅎㅎ..

2023-07-21 14:31 UTC, hurontrara commented on src/main/java/com/server/pickplace/review/controller/ReviewController.java
> +        reviewListMap.put("reviewList", reviewRespons);
map을 데이터로서 리턴하면 json 형태인 key, value 형태에 잘 맞아떨어져서 그렇습니다!

2023-07-21 14:32 UTC, hurontrara commented on src/main/java/com/server/pickplace/search/config/SearchMockUpSetting.java
> +            log.info("------------------------------");
로컬에서 테스트하던걸 지우지 못했네요..

관련 코드를 전부 수정하였습니다!

2023-07-21 14:33 UTC, hurontrara commented on src/main/java/com/server/pickplace/review/controller/ReviewController.java
> +        reviewRepository.amendReview(email, amendReviewRequest, reviewId);
왜 update를 생각못했을까요... 수정하였습니다

2023-07-21 14:43 UTC, hurontrara commented on src/main/java/com/server/pickplace/review/controller/ReviewController.java
> +        reviewRepository.deleteReview(email, reviewId);
1. 시큐리티 단에서 토큰의 유효성 검사를 통과한 코드이므로, 이메일은 존재할 것 같습니다.

2. 리뷰아이디 존재 검증 + 리뷰아이디 해당 리뷰가 본인껀지 검증하는 부분입니다. (ReviewRepositoryCustomImpl 내의 코드입니다)

```
        if (review1 == null) {
            throw new ReviewException(ReviewErrorResult.NO_EXIST_REVIEW_ID);
        } else if (!review1.getReservation().getMember().getEmail().equals(email)) {
            throw new ReviewException(ReviewErrorResult.NO_PERMISSION);
        }
```

3. 일단 토큰에 아이디가 저장되어있지 않은 것으로 알고 있고,
어제 말씀 주신대로 이메일 중복 우려가 있다는 것을 감안하여
멤버 엔티티에 유니크 제약조건을 추가하는 것으로 대체하였습니다!
```
@Table(name = "MEMBER_TB")
public class Member extends BaseEntity implements UserDetails {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MEMBER_ID", nullable = false)
	private Long id;

	@Column(name = "MEMBER_EMAIL", nullable = false, length = 30, unique = true)
	private String email;
```

2023-07-25 15:37 UTC, KangHayeonn commented on src/main/java/com/server/pickplace/review/controller/ReviewController.java
> +        reviewRepository.deleteReview(email, reviewId);
email 쪽에 unique를 걸어줄 필요는 없을 것 같습니다!! 실제 이메일은 중복이 나올 수 있는 거니깐요!
소셜로그인에서 naver.com 을 했는데 일반로그인에서도 동일한 naver.com을 사용할 수도 있으니깐요!!

2023-07-25 15:37 UTC, KangHayeonn approved these changes
확인했습니다! 고생하셨습니다 ㅎㅎ

2023-07-25 16:07 UTC, merged